services:
  - type: web
    name: rizq-platform
    runtime: docker
    repo: https://github.com/ahmadkadri978/rizq-platform
    branch: render
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
    plan: free
    region: oregon
    autoDeploy: true
