spring.application.name=rizq-platform

# ===============================
# = DATABASE CONFIGURATION =
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# = JPA & HIBERNATE CONFIG =
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# = SERVER CONFIG =
# ===============================
server.port=8080

# ===============================
# = SERVER CONFIG =
# ===============================
jwt.secret=V3ryS3cretKeyThatIsLongEnoughToBeSafe2025!!
server.error.whitelabel.enabled=false


# ===============================
# = Email CONFIG =
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rezqplatform@gmail.com
spring.mail.password=yrtq notd qzdz bcez
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


