name: keepalive
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -sSf https://YOUR-RENDER-URL/actuator/health || true
